name = "flora-ong"
compatibility_date = "2026-06-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SOCIOS"
id = "02022a171c04447f86fa4336cbe0c3e0"

[[kv_namespaces]]
binding = "GENETICAS"
id = "9ba2f212388e4ccaa8df118ecca632a7"

[[kv_namespaces]]
binding = "FOTOS"
id = "721e23b4adcc42df8b2871f3aad1604c"

[[kv_namespaces]]
binding = "PEDIDOS"
id = "f5f7e26245e641c6a3b9311351c187fe"

[[kv_namespaces]]
binding = "INTENTOS"
id = "2d141ca74029483f81490cc81c1490e9"

[[kv_namespaces]]
binding = "SOLICITUDES"
id = "e8dfc462239049eb9ce4e2e93425ebe5"
