UPDATE socios SET email = 'ciruzzi1@gmail.com' WHERE nombre = 'Manuel Ciruzzi' AND email IS NULL;
UPDATE socios SET email = 'eliandelmestre1@gmail.com' WHERE nombre = 'Elian Del Mestre' AND email IS NULL;
UPDATE socios SET email = 'fabianvega00018@gmail.com' WHERE nombre = 'Fabian Vega' AND email IS NULL;
UPDATE socios SET email = 'facundo@alta-patagonia.com' WHERE nombre = 'Facundo Vesciglio' AND email IS NULL;
UPDATE socios SET email = 'fai.erickcalderon@gmail.com' WHERE nombre = 'Erick Calderon' AND email IS NULL;
UPDATE socios SET email = 'fernandezcejas@gmail.com' WHERE nombre = 'Hernan Fernandez Cejas' AND email IS NULL;
UPDATE socios SET email = 'garretonepet20@gmail.com' WHERE nombre = 'Franco Garreton' AND email IS NULL;
UPDATE socios SET email = 'garretonssofia@gmail.com' WHERE nombre = 'Sofia Garreton' AND email IS NULL;
UPDATE socios SET email = 'jasna.h.svancara@gmail.com' WHERE nombre = 'Guadalupe Svancara' AND email IS NULL;
UPDATE socios SET email = 'joa88mtz@gmail.com' WHERE nombre = 'Joaquin Martinez' AND email IS NULL;
UPDATE socios SET email = 'juansieg.89@gmail.com' WHERE nombre = 'Juan Sanz' AND email IS NULL;
UPDATE socios SET email = 'julian.rubino0@gmail.com' WHERE nombre = 'Julian Rubino' AND email IS NULL;
UPDATE socios SET email = 'lucasjara899@gmail.com' WHERE nombre = 'Lucas Jara' AND email IS NULL;
UPDATE socios SET email = 'luchochivo1782@gmail.com' WHERE nombre = 'Luciano Sica' AND email IS NULL;
UPDATE socios SET email = 'lulur.gazzola2@gmail.com' WHERE nombre = 'Lourdes Gazzola' AND email IS NULL;
UPDATE socios SET email = 'luzuriaga.jm@gmail.com' WHERE nombre = 'Juan Luzuriaga' AND email IS NULL;
UPDATE socios SET email = 'martin.garcia.duplessis@gmail.com' WHERE nombre = 'Martin Garcia Du Plessis' AND email IS NULL;
UPDATE socios SET email = 'matiascarolvalen@gmail.com' WHERE nombre = 'Matias Carol' AND email IS NULL;
UPDATE socios SET email = 'mauro.aalvarez3@gmail.com' WHERE nombre = 'Mauro Alvarez' AND email IS NULL;
UPDATE socios SET email = 'mehari3cv@gmail.com' WHERE nombre = 'Emiliano Fernandez' AND email IS NULL;
UPDATE socios SET email = 'miguelkobalski@gmail.com' WHERE nombre = 'Miguel Kobalski' AND email IS NULL;
UPDATE socios SET email = 'nmonges28@gmail.com' WHERE nombre = 'Nicolas Monges' AND email IS NULL;
UPDATE socios SET email = 'osoriomauricio640@gmail.com' WHERE nombre = 'Mauricio Osorio' AND email IS NULL;
UPDATE socios SET email = 'pablo.lamas.pl@gmail.com' WHERE nombre = 'Pablo Lamas' AND email IS NULL;
UPDATE socios SET email = 'rodrigo.o.sapag@gmail.com' WHERE nombre = 'Rodrigo Sapag' AND email IS NULL;
UPDATE socios SET email = 'rodrigonobrega9898.rn@gmail.com' WHERE nombre = 'Rodrigo Nobrega' AND email IS NULL;
UPDATE socios SET email = 'rodriguezgomezramiro@gmail.com' WHERE nombre = 'Ramiro Gomez' AND email IS NULL;
UPDATE socios SET email = 'seballamedo@gmail.com' WHERE nombre = 'Sebastian Llamedo' AND email IS NULL;